src/general/urls.py
from django.urls import path

from general.views import IndexView

app_name = 'general'

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

src/orders/urls.py
from django.urls import path

from orders.views import (
    OrderCreateView,
    OrderListView,
    NewOrderListView,
    CompletedOrderListView,
    OrderCompleteView,
    ReceiptCreateView
)


app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('', OrderListView.as_view(), name='list'),
    path('new/', NewOrderListView.as_view(), name='new'),
    path('completed/', CompletedOrderListView.as_view(), name='completed'),
    path('finilize/', ReceiptCreateView.as_view(), name='finilize'),
    path('complete/', OrderCompleteView.as_view(), name='complete'),
]

src/users/urls.py
from django.urls import path

from users.views import UserCreateView, UserLoginView, UserLogoutView


app_name = 'users'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout')
]

src/general/models.py
from django.db import models

# Create your models here.

src/general/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    """
    A welcome view, that greets user and provides him a briefly
    introduction into project features
    """

    template_name = 'general/index.html'

src/general/templates/general/index.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'general/css/index.css' %}">
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<main class="grey lighten-4">
    <section class="section section_welcome green">
        <div class="container">
            <div class="center welcome-wrapper">
                <p class="welcome__upper-text">Welcome to</p>
                <h1 class="welcome__title">Django Hardware Store</h1>
                <p class="welcome__bottom-text grey-text text-lighten-3">
                    A web-application that was designed in order to help the offline shops to automate their workflow, spending less time for accounting, more for serving the customers' needs
                </p>
                <div class="center down-arrow">
                    <a href="#getting-started">
                        <i class="material-icons medium white-text">keyboard_arrow_down</i>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section class="section grey lighten-4">
        <div class="section-title__wrapper">
            <h2 class="section-title__text center" id="getting-started">
                Geting started
            </h2>
        </div>
        <div class="container">
            <div class="start-actions">
                <div class="start-actions__action">
                    <div class="start-actions__action__img center">
                        <i class="material-icons large">person_add</i>
                    </div>
                    <div class="start-actions__text">
                        <h3 class="start-actions__action__title center">Create an account</h3>
                        <p class="start-actions__action__description center">
                            You need to have account created in order to user all of the Django Hardware Store features
                        </p>
                    </div>
                    <div class="start-actions__action___buttons center">
                        <a class="btn waves-effect waves-light blue darken-2"
                            href="{% url 'users:register' %}">
                            Sign up
                        </a>
                    </div>
                </div>
                <div class="start-actions__action">
                    <div class="start-actions__action_img center">
                        <i class="material-icons large">person</i>
                    </div>
                    <div class="start-actions__text">
                        <h3 class="start-actions__action__title center">Sign in system</h3>
                        <p class="start-actions__action__description center">
                            You have to log in your account to get access to Django Hardware Store features
                        </p>
                    </div>
                    <div class="start-actions__action__buttons center">
                        <a class="btn waves-effect waves-light orange darken-2"
                            href="{% url 'users:login' %}">
                            Login
                        </a>
                    </div>
                </div>
                <div class="start-actions__action">
                    <div class="start_actions__action__img center">
                        <i class="material-icons large">import_contacts</i>
                    </div>
                    <div class="start-actions__text">
                        <h3 class="start-actions__action__title center">
                            Visit the orders page
                        </h3>
                        <p class="start-actions__action__description center">
                            If you have already logged in a system - visit the ordering page and begin to work. Follow all the instraction that system gives you
                        </p>
                    </div>
                    <div class="start-actions__action__buttons center">
                        {% if not user.is_authenticated %}
                        <a class="btn waves-effect waves-light red darken-2"
                            href="#!">
                            Start working
                        </a>
                        {% elif user.role == 'cashier' %}
                            <a class="btn waves-effect waves-light red darken-2"
                                href="{% url 'orders:completed' %}">
                                Start working
                            </a>
                        {% elif user.role == 'shop_assistant' %}
                            <a class="btn waves-effect waves-light red darken-2"
                                href="{% url 'orders:new' %}">
                                Start working
                            </a>
                        {% elif user.role == 'accountant' %}
                            <a class="btn waves-effect waves-light red darken-2"
                                href="{% url 'orders:list' %}">
                                Start working
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<footer class="page-footer green darken-1">
    <div class="container">
        <div class="row">
            <div class="col s12 l6">
                <h5 class="white-text">Django Hardware Store</h5>
                <p class="grey-text text-lighten-4">
                    Thank you for choosing our web-application. Plase, folow all the instactions and given links to stcik to proper workflow.
                </p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    {% if not user.is_authenticated %}
                    <li>
                        <a class="grey-text text-lighten-3 link"
                           href="{% url 'users:register' %}">
                            Register
                        </a>
                    </li>
                    <li>
                        <a class="grey-text text-lighten-3 link"
                            href="{% url 'users:login' %}">
                            Login
                        </a>
                    </li>
                    {% else %}
                        {% if user.role == 'shop_assistant' %}
                            <li>
                                <a class="grey-text text-lighten-3 link"
                                    href="{% url 'orders:new' %}">
                                    New orders
                                </a>
                            </li>
                        {% elif user.role == 'cashier' %}
                            <li>
                                <a class="grey-text text-lighten-3 link"
                                    href="{% url 'orders:create' %}">
                                    Create order
                                </a>
                            </li>
                            <li>
                                <a class="grey-text text-lighten-3 link"
                                   href="{% url 'orders:completed' %}">
                                    Completed orders
                                </a>
                            </li>
                        {% elif user.role == 'accountant' %}
                            <li>
                                <a class="grey-text text-lighten-3 link"
                                    href="{% url 'orders:list' %}">Orders list</a>
                            </li>
                        {% endif %}
                        <li>
                            <a class="grey-text text-lighten-3"
                                href="{% url 'users:logout' %}">
                                Logout
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="center">
                © 2020 Vitaliy Diachkov
            </div>
        </div>
    </div>
</footer>
{% endblock %}