src/general/urls.py
from django.urls import path

from general.views import IndexView

app_name = 'general'

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

src/users/urls.py
from django.urls import path

from users.views import UserCreateView, UserLoginView, UserLogoutView


app_name = 'users'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout')
]

src/general/models.py
from django.db import models

# Create your models here.

src/general/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    """
    A welcome view, that greets user and provides him a briefly
    introduction into project features
    """

    template_name = 'general/index.html'

src/general/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Django Hardware Store{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'general/css/materialize.min.css' %}">
    <script type="text/javascript" src="{% static 'general/js/materialize.min.js' %}"></script>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'general/css/global.css' %}">
    <script type="text/javscript" src="{% static 'general/js/global.js' %}"></script>

    {% block links %}{% endblock %}
    {% block style %}{% endblock %}
</head>
<body>
    {% block header %}
        <header>
            <nav class="green">
                <div class="nav-wrapper container">
                    <a href="{% url 'general:index' %}" class="brand-logo">DHS</a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li>
                            <a href="{% url 'general:index' %}">
                                Home
                                <i class="material-icons right">home</i>
                            </a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li>
                                <a href="{% url 'users:login' %}">
                                    Login
                                    <i class="material-icons right">person</i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:register' %}">
                                    Register
                                    <i class="material-icons right">person_add</i>
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'users:logout' %}">
                                    Logout
                                    <i class="material-icons right">exit_to_app</i>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav> 
        </header>
    {% endblock %}
    
    {% block main %}<main></main>{% endblock %}
   {% block script %}{% endblock %}
</body>
</html>