src/orders/urls.py
from django.urls import path

from orders.views import (
    OrderCreateView,
    OrderListView,
    NewOrderListView,
    CompletedOrderListView,
    OrderCompleteView,
    ReceiptCreateView
)


app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('', OrderListView.as_view(), name='list'),
    path('new/', NewOrderListView.as_view(), name='new'),
    path('completed/', CompletedOrderListView.as_view(), name='completed'),
    path('finilize/', ReceiptCreateView.as_view(), name='finilize'),
    path('complete/', OrderCompleteView.as_view(), name='complete'),
]

src/users/urls.py
from django.urls import path

from users.views import UserCreateView, UserLoginView, UserLogoutView


app_name = 'users'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout')
]

src/orders/models.py
from django.db import models

from orders.managers import ReceiptManager
from orders.statuses import OrderStatus


class Order(models.Model):
    """Customer order django model

    Attributes:
        status (int): Current order status (OrderStatus enum)
        create_date (datetime): A date of order creation
        product (Product): A product, that customer wants to buy
    """
    status = models.IntegerField(
        choices=OrderStatus.choices,
        default=OrderStatus.NEW
    )
    create_date = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(
        'products.Product',
        on_delete=models.PROTECT,
        related_name='orders'
    )

    class Meta:
        ordering = ('create_date',)

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()

    def finilize(self):
        self.status = OrderStatus.PAID
        self.save()


class Receipt(models.Model):
    """Order receipt django model

    Receipt is a document that stores data about successfully finished
    deal between store and customer.

    Attribtues:
        total_price (Decimal): Order total price, including discount
        is_discounted (bool): A Boolean variable that shows whether
            discount was granted to shopping
        order (Order): A order that receipt finishes
        create_date (datetime): A date of receipt creation
    """

    total_price = models.DecimalField(max_digits=19, decimal_places=2)
    create_date = models.DateTimeField(auto_now_add=True)
    is_discounted = models.BooleanField(default=False)
    order = models.OneToOneField(
        Order,
        on_delete=models.PROTECT,
        related_name='receipt'
    )

    objects = ReceiptManager()

src/orders/forms.py
from django import forms

from sentry_sdk import capture_message

from products.models import Product

from orders.models import Order, Receipt
from orders.statuses import OrderStatus
from orders.services import validate_order_id


class OrderForm(forms.ModelForm):
    """
    An order creation form
    """

    product = forms.ModelChoiceField(
        queryset=Product.objects.all(),
        empty_label='Select product'
    )

    class Meta:
        model = Order
        fields = ('product',)

    def save(self):
        order = super().save()

        # sentry logging
        capture_message(
            f'A new order with ID {order.id} was created'
            f'(product: {order.product.name})',
            level='info'
        )

        return order


class OrderCompleteForm(forms.Form):
    """
    Gets the new order by its ID and resets its status to COMPLETED
    """

    id = forms.IntegerField()

    def clean_id(self):
        order_id = self.cleaned_data.get('id')
        return validate_order_id(order_id)

    def clean(self):
        cleaned_data = super().clean()

        order = Order.objects.get(id=cleaned_data['id'])

        if order.status != OrderStatus.NEW:
            raise forms.ValidationError(
                'Invalid order status: only new orders can become completed',
                code='invalid_order_status'
            )

        return cleaned_data

    def save(self):
        order = Order.objects.get(id=self.cleaned_data['id'])
        order.complete()

        capture_message(
            f'Order ID {order.id} has chenged status to COMPLETED',
            level='info'
        )

        return order


class ReceiptForm(forms.Form):
    """
    Gets the completed order by ID and resets its status to PAID. Creates
    receipt, based on the given order.
    """

    id = forms.IntegerField()

    def clean_id(self):
        order_id = self.cleaned_data.get('id')
        return validate_order_id(order_id)

    def clean(self):
        cleaned_data = super().clean()
        order = Order.objects.get(id=cleaned_data['id'])

        if order.status != OrderStatus.COMPLETED:
            raise forms.ValidationError(
                f'Only completed order can be finilized',
                code='invalid_order_status'
            )

        return cleaned_data

    def save(self):
        order = Order.objects.get(id=self.cleaned_data['id'])
        return Receipt.objects.create_receipt(
            order=order
        )

src/orders/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView

from rolepermissions.mixins import HasPermissionsMixin

from orders.models import Order
from orders.statuses import OrderStatus
from orders.forms import OrderForm, OrderCompleteForm, ReceiptForm
from orders.filtersets import OrderFilterset


class OrderCreateView(HasPermissionsMixin, CreateView):
    required_permission = 'can_create_order'
    form_class = OrderForm
    template_name = 'orders/create.html'
    success_url = reverse_lazy('orders:completed')


class OrderListView(HasPermissionsMixin, ListView):
    required_permission = 'can_manage_orders'
    template_name = 'orders/list.html'
    paginate_by = 25
    context_object_name = 'orders'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['status'] = {
            'NEW': OrderStatus.NEW,
            'COMPLETED': OrderStatus.COMPLETED,
            'PAID': OrderStatus.PAID
        }

        return context_data
    
    def get_queryset(self):
        return OrderFilterset(
            self.request.GET,
            queryset=Order.objects.all()
        ).qs


class NewOrderListView(HasPermissionsMixin, ListView):
    required_permission = 'can_read_new_order'
    paginate_by = 30
    template_name = 'orders/new.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(status=OrderStatus.NEW)


class CompletedOrderListView(HasPermissionsMixin, ListView):
    required_permission = 'can_read_completed_order'
    paginate_by = 30
    context_object_name = 'orders'
    template_name = 'orders/completed.html'

    def get_queryset(self):
        return Order.objects.filter(status=OrderStatus.COMPLETED)


class OrderCompleteView(HasPermissionsMixin, FormView):
    required_permission = 'can_complete_order'
    form_class = OrderCompleteForm
    success_url = reverse_lazy('orders:new')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ReceiptCreateView(HasPermissionsMixin, FormView):
    required_permission = 'can_create_receipt'
    form_class = ReceiptForm
    success_url = reverse_lazy('orders:completed')
    template_name = 'orders/receipt_create.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

src/orders/templates/orders/completed.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Completed Orders -- Django Hardware Store{% endblock %}

{% block script %}
<script>
    async function finilizeOrderButton() {
        event.preventDefault();

        const form = event.target;
        const orderId = parseInt(form.dataset.id, '10');
        const token = form.querySelectorAll('input[name=csrfmiddlewaretoken]')[0].value;

        const formData = new FormData();
        formData.append('id', orderId);
        
        const response = await fetch(
            "{% url 'orders:finilize' %}",
            {
                method: 'POST',
                headers: {
                    'X-CSRFToken': token,
                },
                body: formData
            }
        );

        if (response.ok) {
            location.reload();
        } else {
            M.toast({
                html: 'Unfortunately, you can not finilize this order at the moment',
                classes: 'red darken-2'
            });
        }
    }    
</script>
{% endblock %}

{% block main %}
<main>
    <section class="section">
        <div class="container">
            <h1>Completed orders</h1>
            <div class="divider"></div>
            <p>
                List of completed orders is presented in a table below. To add new order visit <a href="{% url 'orders:create' %}" class="blue-text text-darken-2 link">order creation page</a>.
            </p>           
            <table class="striped centered responsive-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Product</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.id  }}</td>
                            <td>{{ order.product.name }}</td>
                            <td>{{ order.create_date|date:"H:i A d.m.Y" }}</td>
                            <td>
                                <form onsubmit="finilizeOrderButton();"
                                    data-id={{ order.id }}>
                                    {% csrf_token %}
                                    <button class="btn waves-effect waves-light
                                        red darken-2">
                                        Finilize
                                        <i class="material-icons right">done</i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</main>
{% endblock %}

src/orders/templates/orders/create.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Create Order -- Django Hardware Store{% endblock %}


{% block script %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);

        {% if message %}
            M.toast({
                html: '{{ message }}',
                classes: 'green darken-2'
            });
        {% endif %}

        {% if errors %}
            M.toast({
                html: 'Please, select an option',
                classes: 'red darken-2'
            });
        {% endif %}
    });
</script>
{% endblock %}

{% block main %}
<main>
    <section class="section">
            <div class="container">
            <h1>Create order</h1>
            <div class="divider"></div>
            
            <form method="post" action="{% url 'orders:create' %}" novalidate>
                {% csrf_token %}
                <div class="row">
                    <div class="col s12 input-field">
                        {{ form.product }}
                    </div>
                    <div class="col s12 center">
                        <button class="btn-large red darken-2 waves-effect waves-light">
                            Submit
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</main>
{% endblock %}

src/orders/templates/orders/list.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %}Orders -- Django Hardware Store{% endblock %}


{% block script %}
<script>
    function getURLQueryParam(param) {
        if (!param) {
            return;
        }

        const url = new URL(location.href);
        return url.searchParams.get(param);
    }

    function getStartDate() {
        const url = new URL(location.href);
        const year = url.searchParams.get('create__year__gte');
        const month = url.searchParams.get('create__month__gte');
        const day = url.searchParams.get('create__day__gte');
        
        if (!year || !month || !day) {
            return;
        } else {
            return new Date(year, month - 1, day);
        }
    }

    function getEndDate() {
        const url = new URL(location.href);
        const year = url.searchParams.get('create__year__lte');
        const month = url.searchParams.get('create__month__lte');
        const day = url.searchParams.get('create__day__lte');

        if (!year || !month || !day) {
            return;
        } else {
            return new Date(year, month - 1, day);
        }
    }

    function setDatepickerDate(id, date) {
        const datepicker = document.getElementById(id);
        const instance = M.Datepicker.getInstance(datepicker);
        
        instance.setDate(date);
        options = {
            year: 'numeric',
            month: 'short',
            day: '2-digit'
        };
        
        datepicker.value = date.toLocaleDateString('en', options);

    }

    document.addEventListener('DOMContentLoaded', function() {
        var datepickers = document.querySelectorAll('.datepicker');
        var dpInstances = M.Datepicker.init(datepickers);

        const startDate = getStartDate();

        if (startDate) {
            setDatepickerDate('orderStartDatePicker', startDate);
        }

        const endDate = getEndDate();

        if (endDate) {
            setDatepickerDate('orderEndDatePicker', endDate);
        }

        const statusSelect = document.getElementById('orderStatusSelect');
        const status = getURLQueryParam('status');

        if (status) {
            statusSelect.value = status;
        }

        var selects = document.querySelectorAll('select');
        var sInstances = M.FormSelect.init(selects);
    });

    function appendURLQueryParam(url, param, value) {
        if (!url || !param || !value) {
            return location.href;
        }

        const newURL = new URL(url);
        newURL.searchParams.set(param, value);
        return newURL.toString();
    }

    function deleteURLQueryParam(ulr, param) {
        if (!url || !param) {
            return location.href;
        }

        const newURL = new URL(url);
        if (Array.isArray(param)) {
            for (const paramName of param) {
                newURL.searchParams.delete(paramName);
            }
        } else {
            newURl.searchParams.delete(param);
        }

        return newURL.toString();
    }

    async function orderStatusSelectOnchangeHandler() {
        const status = event.target.value;
        let redirectURL = '';

        if (status) {
            redirectURL = appendURLQueryParam(location.href, 'status', status);        
        } else {
            redirectURL = deleteURLQueryParam(location.href, 'status');
        }
        
        location.replace(redirectURL);
    }

    async function orderStartDateOnchangeHandler() {
        const datepicker = M.Datepicker.getInstance(event.target);
        let redirectURL = '';
        const date = datepicker.date;

        if (datepicker.toString()) {
            redirectURL = appendURLQueryParam(
                location.href,
                'create__year__gte',
                date.getFullYear()
            );
            redirectURL = appendURLQueryParam(
                redirectURL,
                'create__month__gte',
                date.getMonth() + 1
            );
            redirectURL = appendURLQueryParam(redirectURL, 'create__day__gte', date.getDate());
        } else {
            redirectURL = deleteURLQueryParam(location.href, [
                'create__year__gte',
                'create__month__gte',
                'create__day__gte'
            ]);
        }
        
        location.replace(redirectURL);
    }

    async function orderEndDateOnchangeHandler() {
        const datepicker = M.Datepicker.getInstance(event.target);
        let redirectURL = '';
        const date = datepicker.date;

        if (datepicker.toString()) {
            redirectURL = appendURLQueryParam(
                location.href,
                'create__year__lte',
                date.getFullYear()
            );
            redirectURL = appendURLQueryParam(
                redirectURL,
                'create__month__lte',
                date.getMonth() + 1
            );
            redirectURL = appendURLQueryParam(
                redirectURL,
                'create__day__lte',
                date.getDate()
            );
        } else {
            redirectURL = deleteURLQueryParam(location.href, [
                'create__year__lte',
                'create__month__lte',
                'create__day__lte'
            ]);
        }

        location.replace(redirectURL);
    }
</script>
{% endblock %}


{% block main %}
    <main>
        <section class="section">
            <div class="container">
                <h1>Orders</h1>
                <div class="divider" style="margin-bottom: 20px;"></div>

                <div class="row">
                    <div class="col s12 input-field">
                        <select id="orderStatusSelect" name="orderStatusSelect"
                            onchange="orderStatusSelectOnchangeHandler();">
                            <option value="" selected>Select all</option>
                            <option value="{{ status.NEW }}">Select new orders</option>
                            <option value="{{ status.COMPLETED }}">Select completed orders</option>
                            <option value="{{ status.PAID }}">Select paid orders</option>
                        </select>
                    </div>
                    <div class="col s12 l6 input-field">
                        <input type="text" class="datepicker"
                            id="orderStartDatePicker"
                            placeholder="From"
                            onchange="orderStartDateOnchangeHandler();">
                    </div>
                    <div class="col s12 l6 input-field">
                        <input type="text" class="datepicker"
                            id="orderEndDatePicker"
                            placeholder="To"
                            onchange="orderEndDateOnchangeHandler();">
                    </div>
                </div>

                <table class="responsive-table striped centered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Product</th>
                            <th>Date</th>
                            <th>Total price</th>
                            <th>Discounted</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in page_obj %}
                        <tr>
                            <td>{{ order.id  }}</td>
                            <td>{{ order.product.name }}</td>
                            <td>{{ order.create_date|date:"H:i A d.m.Y" }}</td>
                            {% if order.receipt %}
                                <td>{{ order.receipt.total_price  }}</td>
                                <td>{{ order.receipt.is_discounted }}</td>
                            {% else %}
                                <td>-</td>
                                <td>-</td>
                            {% endif %}
                        </tr>
                        {% empty %}
                        <tr>
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="center">
                {% if page_obj.paginator.num_pages > 1 %}
                <div class="pagination">
                    <li><a href="?page=1"><i class="material-icons">chevron_left</i></a></li>
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}"
                                class="waves-effect">
                                {{ page_obj.previous_page_number }}
                            </a>
                        </li>
                    {% endif %}

                    <li>
                        <a href="#!" class="active green waves-effect waves-light white-text">
                            {{ page_obj.number }}
                        </a>
                    </li>

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}"
                                class="waves-effect">
                                {{ page_obj.next_page_number }}
                            </a>
                        </li>
                    {% endif %}

                    <li>
                        <a href="?page={{ page_obj.paginator.num_pages }}">
                            <i class="material-icons">
                                chevron_right
                            </i>
                        </a>
                    </li>
                </div>
                {% endif %}
            </div>
        </section>
    </main>
{% endblock %}

src/orders/templates/orders/new.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %}New Orders -- Django Hardware Store{% endblock %}

{% block script %}
<script>
    async function completeOrder() {
        event.preventDefault();

        const form = event.target;
        const orderId = parseInt(form.dataset.id, '10');
        const token = form.querySelectorAll('input[name=csrfmiddlewaretoken]')[0].value;

        const formData = new FormData();
        formData.append('id', orderId);

        const response = await fetch(
            "{% url 'orders:complete' %}",
            {
                method: 'POST',
                headers: {
                    'X-CSRFToken': token,
                },
                body: formData
            }
        );

        console.log(response.status);
        if (response.ok) {
            location.reload();
        } else {
            M.toast({
                html: 'Unfortunately, you can not complete this order at the moment',
                classes: 'red darken-2'
            });
        }
    }
</script>
{% endblock %}

{% block main %}
    <main>
        <section class="section">
            <div class="container">
                <h1>New Orders</h1>
                <div class="divider"></div>

                <table class="responsive-table striped centered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Product</th>
                            <th>Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.id  }}</td>
                                <td>{{ order.product.name  }}</td>
                                <td>{{ order.create_date|date:"H:i A d.m.Y" }}</td>
                                <td>
                                    <form onsubmit="completeOrder();"
                                        data-id={{ order.id }}>
                                        {% csrf_token %}
                                        <button class="btn red darken-2 waves-effect
                                            waves-light">
                                            Complete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </main>
{% endblock %}